complexTable/urls.py
from django.urls import path

from . import views

app_name = 'complexTable'

# Patterns which leads to a page
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('complexTable', views.ComplexView.as_view(), name='complexTable'),
    path('detailedInfo', views.DetailedView.as_view(), name='detailedInfo'),
]

# Patterns which leads to download
downloadpatterns = [
    path('download', views.download, name='download'),
    path('downloadFiles', views.downloadFiles, name='downloadFiles'),
    path('downloadPOST', views.downloadPOST, name='downloadPOST'),
]

# Patterns to work with ajax
ajaxpatterns =[
    path('hist_post', views.hist_post, name='hist_post'),
    path('line2d_post', views.line2d_post, name='line2d_post'),
    path('heat2d_post', views.heat2d_post, name='heat2d_post'),
    path('distrib2d_post', views.distrib2d_post, name='distrib2d_post'),
    path('facet2d_post', views.facet2d_post, name='facet2d_post'),
]

# Concatenate all lists
urlpatterns += downloadpatterns
urlpatterns += ajaxpatterns

ligmol/urls.py
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('complexTable.urls')),
]#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

complexTable/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PostHistogram(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    text = models.TextField()

    # Time is a rhinocerous
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __unicode__(self):
        return self.text + ' - ' + self.author.username

class Complex(models.Model):
    length = 200

    # Fields
    id = models.IntegerField(primary_key=True)
    Complex = models.CharField(max_length=length, blank=False, null=False, default='unknown')
    host = models.CharField(max_length=length, blank=False, null=False, default='unknown')
    guest = models.CharField(max_length=length, blank=False, null=False, default='unknown')
    gbmodel = models.IntegerField()
    intdiel = models.IntegerField()
    saltcom = models.FloatField()
    average = models.CharField(max_length=length, blank=False, null=False, default='unknown')
    mmgbsa = models.FloatField()
    nma = models.FloatField()
    deltag = models.FloatField()
    exp = models.FloatField()
    challenge = models.CharField(max_length=length, blank=False, null=False, default='unknown')
  
    # Metadata
    class Meta:
        ordering = ('id', 'Complex', 'host', 'guest', 'gbmodel',
         'intdiel', 'saltcom', 'average', 'mmgbsa', 'nma', 'deltag', 'exp', 'challenge' ) 
         # helps in alphabetical listing. Sould be a tuple

    def __str__(self):
        # It is not a nice print but it is sort of readable (SORT OF)
        return ', '.join('{}{}'.format(key, val) for key, val in self.__dict__.items())

complexTable/forms.py
import re

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

### CUSTOM VALIDATORS ###

def validate_path(value):
    if not re.match(r'^[a-zA-Z0-9+_.]*$', value):
        raise forms.ValidationError('Invalid value')

class HistForm(forms.Form):
    mincutoff = forms.FloatField(label='min cutoff', required=False)
    maxcutoff = forms.FloatField(label='max cutoff', required=False)

class CheckForm(forms.Form):
    choices = forms.MultipleChoiceField(
        widget = forms.CheckboxSelectMultiple(),
        choices = list(map(list, zip(*[list(range(0, 100000)),list(range(0, 100000))])))
    )

class TwodmapFormLine(forms.Form):
    types2d = forms.ChoiceField(
        choices = [("simple", "Simple plot"), ("runningAvg", "Running Average plot")],
        initial = 'simple',
        widget = forms.RadioSelect(),
        required = False
    )
    mincutoff2d = forms.FloatField(label='min cutoff: ', required=False, initial = 0)
    maxcutoff2d = forms.FloatField(label='max cutoff: ', required=False)

class TwodmapFormHeat(forms.Form):
    mincutoffheat2d = forms.FloatField(label='min cutoff: ', required=False, initial = 0)
    maxcutoffheat2d = forms.FloatField(label='max cutoff: ', required=False)

class TwodmapFormDistrib(forms.Form):
    types2ddistrib = forms.ChoiceField(
        choices = [("strip", "Strip plot"), ("box", "Box plot"), ("violin", "Violin plot")],
        initial = 'strip',
        widget = forms.RadioSelect(),
        required = False
    )
    mincutoffdistrib2d = forms.FloatField(label='min cutoff: ', required=False, initial = 0)
    maxcutoffdistrib2d = forms.FloatField(label='max cutoff: ', required=False)

class TwodmapFormFacet(forms.Form):
    types2dfacet = forms.ChoiceField(
        choices = [("fg", "Facet Grids"), ("fgrolling", "Facet Grids Rolling"), ("fgdistplot", "Facet Grid Dist Plot"), ("fgseparate", "Facet Grids Separate")],
        initial = 'fg',
        widget = forms.RadioSelect(),
        required = False
    )
    mincutofffacet2d = forms.FloatField(label='min cutoff: ', required=False, initial = 0)
    maxcutofffacet2d = forms.FloatField(label='max cutoff: ', required=False)

class FilesSubfiles(forms.Form):
    # choices = forms.MultipleChoiceField(
    #     widget  = forms.CheckboxSelectMultiple,
    #     validators=[validate_path]
    # )
    choices = forms.CharField(
        widget=forms.SelectMultiple
    )

complexTable/views.py
# Django imports
import seaborn as sns
import pandas as pd
import tarfile
import logging
import base64
import json
import csv
import re
import os
from wsgiref.util import FileWrapper
from ast import literal_eval
from io import BytesIO
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.conf import settings
from django.template.defaulttags import register
from django.http import HttpResponse, Http404
from django.views.generic.edit import FormView

# Models import
from complexTable.models import Complex
from complexTable.forms import *

# Special python imports
import matplotlib
matplotlib.use('Agg')

# Late imports
from matplotlib.dates import DateFormatter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib import pyplot as plt


# Graphic spacing variables
spacing = 15
tsSpacing = 5

# Logger to log
logger = logging.getLogger(__name__)

# region Graphic filters


def hist_post(request):
    """
    Deals with the post data to process the histogram
    """

    # If is POST
    if request.method == 'POST':

        # Get the POST data in HistForm
        form = HistForm(request.POST)

        # If the form is valid
        if form.is_valid():
            # Read max and min cutoff values from POST
            mincutoff = form.cleaned_data['mincutoff']
            maxcutoff = form.cleaned_data['maxcutoff']

            # Parse the histogram
            preHistogram = parseHistogram()

            # Read info from parsed histogram dictionary
            datas = preHistogram["datas"]
            names = preHistogram["names"]

            # Compute the length of graphic
            sizeHist = len(datas)
            datasLen = len(datas[0])

            # List to hold which data will be deleted (should be reverse deletion)
            deleter = []

            # If both restrictions are imposed
            if mincutoff != None and maxcutoff != None:
                # For each serie in dataset
                for index in range(1, datasLen):
                    # For each element in the serie
                    for innerIndex in range(0, sizeHist):
                        # If the element does not respect restrictions
                        if datas[innerIndex][index] < mincutoff or datas[innerIndex][index] > maxcutoff:
                            # Flag its index to delete it (decrescent)
                            deleter.insert(0, index)
                            break

            # If only an upper bound is imposed
            elif mincutoff == None and maxcutoff != None:
                # For each serie in dataset
                for index in range(1, datasLen):
                    # For each element in serie
                    for innerIndex in range(0, sizeHist):
                        # If the element does not respect the restriction
                        if datas[innerIndex][index] > maxcutoff:
                            # Flag its index to delete it (decrescent)
                            deleter.insert(0, index)
                            break

            # If only a lower bound is imposed
            elif mincutoff != None and maxcutoff == None:
                # For each serie in dataset
                for index in range(1, datasLen):
                    # For each element in serie
                    for innerIndex in range(0, sizeHist):
                        # If the element does not respect the restriction
                        if datas[innerIndex][index] < mincutoff:
                            # Flag its index to delete it (decrescent)
                            deleter.insert(0, index)
                            break

            # If there are any flagged index to delete
            if deleter:
                # For each flagged item (this is a decrescent list)
                for delet in deleter:
                    # Delete its name
                    del names[delet-1]

                    # For each serie in dataset
                    for index in range(0, sizeHist):
                        # Delete the element from data serie
                        del datas[index][delet]

            # Create de histogram dictionary
            histogram = {}

            # Add info to it
            histogram["names"] = names
            histogram["datas"] = datas
            histogram["dsize"] = len(datas) * spacing

            # Create the response data object (dictionary)
            response_data = {}

            # Define a default size
            size = 0

            # If there is any name
            if names:
                # Set its size
                size = (len(names) + 1) * spacing

                # Start to create the print data
                toPrint = "\n\tvar chart = c3.generate({\n\t\tbindto: '#show-histogram',\n\t\tdata: {\n\t\t\tcolumns: [\n\t"

                # Get size of dataset
                dataslen = len(datas) - 1

                # For each serie in dataset
                for index, data in enumerate(datas):
                    # Append more info
                    toPrint = toPrint + "\t\t["

                    # Get the length of serie
                    datalen = len(data) - 1

                    # For each element in serie
                    for innerIndex, info in enumerate(data):
                        # If is the first element
                        if innerIndex == 0:
                            # It's the name
                            toPrint = toPrint + "'" + str(info) + "'"
                        else:
                            # Its a number
                            toPrint = toPrint + str(info)

                        # If its not last element
                        if not innerIndex == datalen:
                            # Add a comma
                            toPrint = toPrint + ", "

                    # If its not the last element
                    if not index == dataslen:
                        # Close the bracket and add comma
                        toPrint = toPrint + "],\n\t"
                    else:
                        # Jus close the bracket
                        toPrint = toPrint + "]\n\t"

                # Add more info to print
                toPrint = toPrint + \
                    "\t],\n\t\ttype: 'bar'\n\t\t},\n\t\tsize: {\n\t\t\theight: 600,\n\t\t\twidth: "

                # If the size is lower than 400 (small graphic)
                if size < 400:
                    # If is smaller than 380 (small graphic)
                    if size <= 380:
                        # Set its size to 400
                        toPrint = toPrint + "400"
                    else:
                        # Since is a not so small graphic, the graphic will have its size between 400 and 420
                        toPrint = toPrint + str(420-size)
                else:
                    # Otherwise the graphic will have the size itself
                    toPrint = toPrint + str(size)

                # Add more info
                toPrint = toPrint + \
                    "\n\t\t},\n\t\tpadding: {\n\t\t\tbottom: 80,\n\t\t\tright: 20\n\t\t},\n\t\taxis: {\n\t\t\tx: {\n\t\t\t\ttype: 'category',\n\t\t\t\ttick: {\n\t\t\t\t\trotate: 60,\n\t\t\t\t\tmultiline: false\n\t\t\t\t},\n\t\t\t\tcategories: ["

                # Compute the length of names
                nameslen = len(names) - 1

                # For each name in names
                for index, name in enumerate(names):
                    # Append it (will be label)
                    toPrint = toPrint + "'" + str(name) + "'"

                    # If its not the last index
                    if not index == nameslen:
                        # Add a comma
                        toPrint = toPrint + ", "

                # Append more info
                toPrint = toPrint + \
                    "]\n\t\t\t}\n\t\t},\n\t\tbar: {\n\t\t\twidth: {\n\t\t\t\tratio: 0.7\n\t\t\t}\n\t\t}\n\t});\n"
            else:
                # Throw an error
                toPrint = "alert('No results matching your filter!');"

            # Add all the data to response_data
            response_data["script"] = toPrint

            # Process names sizes
            if names:
                # If its smaller than 400
                if size < 400:
                    # Set its size to 400
                    response_data["style"] = "\n\t.html2canvas-container\n\t{\n\t\twidth: " + str(
                        400) + "px !important;\n\t\theight: 600px !important;\n\t}"
                else:
                    # Otherwise keep its size
                    response_data["style"] = "\n\t.html2canvas-container\n\t{\n\t\twidth: " + str(
                        size) + "px !important;\n\t\theight: 600px !important;\n\t}"
            else:
                # Since there is no name, there is no style to apply
                response_data["style"] = ""

            # Return the http response as a json
            return HttpResponse(
                json.dumps(response_data),
                content_type="application/json"
            )

    else:
        # Since is not POST, return a dummy json
        return HttpResponse(
            json.dumps(
                {"nothing to see": "You're not suppose to sniff this."}),
            content_type="application/json"
        )


def line2d_post(request):
    """
    Deals with the post data to process the line plot
    """

    # If is POST
    if request.method == 'POST':
        # Get the POST data in TwodmapFormLine
        form = TwodmapFormLine(request.POST)

        # If the form is valid
        if form.is_valid():
            # Read max, min cutoff and types2d values from POST
            mincutoff2d = form.cleaned_data['mincutoff2d']
            maxcutoff2d = form.cleaned_data['maxcutoff2d']
            choice = form.cleaned_data['types2d']

complexTable/templates/complexTable/complexTable.html
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - LigMol</title>
    <meta name="description" content="A simple complex database">
    <link rel="stylesheet" href="{% static 'complexTable/bootstrap/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'complexTable/img/favicon.ico' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:700">
    <link rel="stylesheet" href="{% static 'complexTable/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'complexTable/custom.css' %}">
    <script src="{% static 'complexTable/js/sorttable.js' %}"></script>
    <!--Plugin CSS file with desired skin-->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css" />

    <!--jQuery-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!--Plugin JavaScript file-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>

</head>

<body id="page-top">
    <nav class="navbar navbar-light navbar-expand-md navbar navbar-expand-lg fixed-top" id="mainNav"
        style="background-color: #829eaa;">
        <div class="container"><a class="navbar-brand js-scroll-trigger"
                href="{% url 'complexTable:index' %}">LigMol</a><button class="navbar-toggler navbar-toggler-right"
                data-toggle="collapse" data-target="#navbarResponsive" type="button" aria-controls="navbarResponsive"
                aria-expanded="false" aria-label="Toggle navigation" value="Menu"><i class="fa fa-bars"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item nav-link js-scroll-trigger pointer" role="presentation"><a
                            class="nav-link js-scroll-trigger"
                            onclick="location.href='{% url 'complexTable:index' %}' + '#home'">Home</a></li>
                    <li class="nav-item nav-link js-scroll-trigger pointer" role="presentation"><a
                            class="nav-link js-scroll-trigger"
                            onclick="location.href='{% url 'complexTable:index' %}' + '#about'">About</a></li>
                    <li class="nav-item nav-link js-scroll-trigger pointer" role="presentation"><a
                            class="nav-link js-scroll-trigger"
                            onclick="location.href='{% url 'complexTable:index' %}' + '#contact'">contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <section id="complexTable">
        <div class="row">
            <div style='margin-top:90;'></div>
        </div>
        <br />
        <div class="row">
            <div class="container">
                <h2>Compounds</h2>
                <!-- <p>Type something in the input field to filter the table:</p>
                <input class="form-control" id="tableSearch" type="text" placeholder="Search.."> -->
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-2 center">
                <div class="sticky-top" style="top: 130px;">
                    <input value="Download checked items" type="submit" form='downForm' class="btn" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="table-responsive">
                    <form id='downForm' onsubmit="return checkChecks(event)" action="downloadFiles" method="post">
                        {% csrf_token %}
                        <table id='compoundTable' class="table table-striped table-hover container-fluid sortable"
                            valign="center" style="width:65%; height:70%; text-align:center;">
                            <thead>
                                <tr>
                                    <th scope="col" valign="center"><input valign="center" style="margin-left: 12px;"
                                            type="checkbox" name="checkAll" id="select_all" onClick=""></th>
                                    {% for key in keys %}<th scope="col" valign="center">{{ key }}</th>{% endfor %}
                                </tr>
                            </thead>
                            <tbody id='compoundBody'>
                                {% for bigID, orderDict in table.items %}<tr class='limitedHeight'
                                    onclick="showMeDetails({{ bigID }})">
                                    <td class='center' valign="center"'>
                                        <input valign="center" class="form-check-input" style="margin-left: 0px;" type="checkbox" name="choices" id="choicesID" value="{{ bigID }}">
                                    </td>
                                    {% for key, val in orderDict.items %}
                                    <td class="clickable {{ key }}col" style="cursor: pointer"; valign="center">{{ val }}</td>
                                    {% endfor %}
                                </tr>{% endfor %}
                            </tbody>
                        </table>
                        <script>
                            function showMeDetails(bigid) {
                                window.onclick = function (e) {
                                    if (e.srcElement.className == "clickable") {
                                        window.location.href = "{% url 'complexTable:detailedInfo' %}?id=" + bigid;
                                    }
                                }
                            }
                        </script>
                    </form>
                </div>
            </div>
            <div class="col-3 center">
                    <div class="sticky-top" style="top: 130px;">
                <div class="container">
                    {% with 'GBMODEL INTDIEL SALTCOM MMGBSA NMA DELTA_G exp' as numList %}
                        {% with 'GBMODEL INTDIEL' as intList %}
                            {% for key in keys %}
                                {% if forloop.counter|divisibleby:2 %}
                                    <div class="col" style="margin-left: 10px;">
                                {% else %}
                                    <div class="row">
                                        <div class="col" style="margin-right: 10px;">
                                {% endif %}
                                {{ key }}
                                {% if key in numList.split %}
                                    <input id="{{ key|toLower }}filter" type="text" class="js-range-slider personalFilterNum" value="" />
                                    <script>
                                        $(".js-range-slider").ionRangeSlider({
                                            type: "double",
                                            skin: "square",
                                            step: {% if key in intList.split %}1{% else %}0.01{% endif %},
                                            min: {{ table|get_item_min:key }},
                                            max: {{ table|get_item_max:key }},
                                            from: {{ table|get_item_min:key }},
                                            to: {{ table|get_item_max:key }},
                                            grid: true,
                                            decorate_both: true,
                                            values_separator: " to ",
                                            drag_interval: true,
                                            onChange: function(data){
                                                ligmol.updateTbl();
                                            }
                                        });
                                    </script>
                                {% else %}
                                <br/>
                                <select class="form-control personalFilterStr" id="{{ key|toLower }}filter" placeholder="Search in {{ key|toLower }} column..." style="width: 100%;">
                                    <option value="none">None</option> 
                                </select>
                                <!-- <input class="form-control personalFilterStr" id="{{ key|toLower }}filter" type="text" placeholder="Search in {{ key|toLower }} column..."> -->
                                {% endif %}
                                {% if forloop.counter|divisibleby:2%}
                                    </div>
                                </div>
                                {% else %}
                                </div>
                                {% endif %}
                                {% if not forloop.last %}
                                    <br/>
                                {% endif %}
                            {% endfor %}
                        {% endwith %}
                    {% endwith %}
                </div>
            </div>
            </div>
            <div class="col-1"></div>
        </div>
    </section>
    
    <footer>
        <div class="container text-center">
            <p>Copyright ©&nbsp;LigMol 2018</p>
        </div>
    </footer>
    <script src="{% static 'complexTable/js/jquery.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="{% static 'complexTable/js/grayscale.js' %}"></script>
    <script src="{% static 'complexTable/js/ligmol.js' %}"></script>
</body>
</html>